"""Question type taxonomy and classification for the quizzer module."""

from dataclasses import dataclass
from enum import Enum


class QuestionType(str, Enum):
    """Types of questions the quizzer can generate."""

    YES_NO = "yes_no"
    NUMERICAL = "numerical"
    CONDITIONAL = "conditional"
    FACTUAL = "factual"
    COMPARISON = "comparison"
    PROCEDURAL = "procedural"


# Weights control how often each question type is generated.
# Heavier weights = more questions of that type.
QUESTION_TYPE_WEIGHTS: dict[QuestionType, float] = {
    QuestionType.YES_NO: 0.15,
    QuestionType.NUMERICAL: 0.15,
    QuestionType.CONDITIONAL: 0.15,
    QuestionType.FACTUAL: 0.25,
    QuestionType.COMPARISON: 0.10,
    QuestionType.PROCEDURAL: 0.20,
}

QUESTION_TYPE_DESCRIPTIONS: dict[QuestionType, str] = {
    QuestionType.YES_NO: (
        "A yes/no question about coverage, eligibility, or policy features. "
        'Example: "Does Harel car insurance cover windshield damage?"'
    ),
    QuestionType.NUMERICAL: (
        "A question asking for specific numbers: amounts, percentages, limits, "
        'dates, or durations. Example: "What is the maximum coverage amount '
        'for travel medical expenses?"'
    ),
    QuestionType.CONDITIONAL: (
        "A question about conditions, exceptions, or scenarios. "
        'Example: "What happens if I cancel my travel insurance after departure?"'
    ),
    QuestionType.FACTUAL: (
        "A direct factual question about policy details, coverage, or terms. "
        'Example: "What does the comprehensive car insurance policy include?"'
    ),
    QuestionType.COMPARISON: (
        "A question comparing options, plans, or different aspects of coverage. "
        'Example: "What is the difference between basic and premium health plans?"'
    ),
    QuestionType.PROCEDURAL: (
        "A how-to question about processes, claims, or steps. "
        'Example: "How do I file a claim for apartment damage?"'
    ),
}


@dataclass
class GeneratedQuestion:
    """A single question generated by the quizzer."""

    question: str  # The casual-chat question text
    question_type: QuestionType
    domain: str  # Insurance domain
    source_documents: list[dict]  # Documents containing the answer
    expected_answer: str  # Concrete ground truth answer from source docs
    expected_answer_hints: str  # Key points the answer should cover
    language: str  # "he" or "en"
    difficulty: str  # "easy", "medium", "hard"
